### ISSUE TITLE
Can't run Shopping Cart app.

### ISSUE THREAD

**Issue by GTamara** [krakenjs/kraken-example-with-shoppingcart#17]
Dear Kraken's team,
I'm working on Ubuntu Linux 14.04 and 0.10.25 nodejs.
I had tried to run the app using your instructions,
I got the following error message:
Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version.
Please, see attachment.

[npm-debug .log.txt](https://github.com/krakenjs/kraken-example-with-shoppingcart/files/336407/npm-debug.log.txt)

On waiting for your answer.
Best regards,
Tamara.

**Comment by grawk** [comment]
Hi @GTamara I wonder if you could try again with node v4 or newer? We may have broken compatibility with v0.10 in a recent change.

**Comment by anythingcodes** [comment]
I had this problem too on Node v6.9.2 for Windows 10 x64.

Copying `node_modules\bson\browser_build\bson.js` to `node_modules\bson\build\Release\bson.js` worked for me. 

Alternatively, you could update the `require()` references in `node_modules`.
